App/urls.py
from django.conf.urls import url
from django.urls import path,include
from App import views

app_name='App'

urlpatterns=[
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),

]

LabApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
from App import views


urlpatterns = [
    path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('login/', include('App.urls')),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('dashboard/',views.dashboard,name="dashboard"),
    path('dashboard/<int:pk>/',views.DeleteComplains.as_view(),name="DeleteComplains"),
    path('dashboard/create', views.ComplainsCreateView.as_view(), name='ComplainCreate'),
    path('Notice/',views.NoticeBoard.as_view(),name="Notice"),
    path('Notice/create', views.NoticeCreateView.as_view(), name='NoticeCreate'),
    path('Attendent/',views.AttendentDetails.as_view(),name="Attendent"),
    path('Faculty/',views.FacultyDetails.as_view(),name="Faculty"),
    path('TimeTable/',views.TimeTable.as_view(),name="TimeTable"),
    path('Attendent_dashboard/<int:pk>/',views.StatusUpdate.as_view(),name="StatusUpdate"),
    path('dashboard_Att/',views.Dash.as_view(),name="dashboard_Att"),

]

App/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


#class LabInfo(models.Model):
 #   LabName = models.CharField(blank=True,max_length=20)
  #  LabCapacity = models.IntegerField(null=True)
  #  SoftwareInstalled = models.TextField(null=True)

    #def __str__(self):
      #  return self.LabName

class LabInf(models.Model):
    Name = models.CharField(blank=True,max_length=100)
    LabCapacity=models.IntegerField()
    Software=models.TextField()

    def __str__(self):
        return self.Name


class LabTeacher(models.Model):
    TeacherName = models.CharField(blank=True,max_length=20,primary_key=True)
    #Department = models.CharField(blank=True, max_length=20)
    Contact = models.IntegerField()

    def __str__(self):
        return self.TeacherName


class LabAttendent(models.Model):
    AttendentName = models.CharField(blank=True,max_length=20,primary_key=True)
    LabAssigned = models.TextField()
    Contact = models.IntegerField()

    def __str__(self):
        return self.AttendentName



class Complains(models.Model):
    LabName = models.ForeignKey(LabInf, on_delete=models.CASCADE)
    Issue = models.TextField()
    ResolvedValue = models.BooleanField()
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)



class LabSchedule(models.Model):
    LabName =models.ForeignKey(LabInf, on_delete=models.SET_NULL, null=True,)
    TimeSlot = models.CharField(blank=True,max_length=7)
    Batch = models.CharField(blank=True,max_length=8)
    Day = models.CharField(blank=True,max_length=13)
    Subject = models.CharField(blank=True,max_length=10)
    TeacherName=models.ForeignKey(LabTeacher,on_delete = models.SET_NULL, null=True)


class Notice(models.Model):
        IssuedOn = models.DateField()
        Text = models.TextField()


#class FreeSlotBooking(models.Model):
 #   TimeSlot=models.ForeignKey(LabSchedule,on_delete=models.SET_NULL, null=True,related_name='Time')
  #  BookedBy=models.ForeignKey(LabTeacher,on_delete=models.SET_NULL, null=True)
   # Day=models.ForeignKey(LabSchedule,on_delete=models.SET_NULL, null=True,related_name='day')

App/forms.py
from django import forms
from django.contrib.auth.models import User
from App.models import *
from django.http import HttpResponseRedirect,HttpResponse


class ComplainForm(forms.ModelForm):
    class Meta():
        model = Complains
        fields = ['LabName',  'Issue', 'ResolvedValue']


class NoticeForm(forms.ModelForm):
    class Meta():
        model = Notice
        fields = ['IssuedOn', 'Text']


class TimeTableForm(forms.ModelForm):
    class Meta():
        model = LabSchedule
        fields = ['Day','LabName']


class UpdateIssueStatusForm(forms.ModelForm):
    class Meta():
        model = Complains
        fields = ['LabName','ResolvedValue']

App/views.py
from django.shortcuts import render,redirect

from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from django.contrib.auth.models import User
from django.views import generic

from django.urls import reverse_lazy

from App.forms import *
from App.models import *
# Create your views here.


def index(request):
    return render(request,'App/index.html')


def user_login(request):
    print("login page attempt")
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        print(username)
        print(password)
        user = authenticate(username=username, password=password)

        if user is not None:
            #if user.is_active():
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            #else:
                #return HttpResponse("Account Not Active")
        else:
            print("false login")
            return HttpResponseRedirect(reverse('login'))
    else:
        print("render part ran successfully")
        return render(request,'App/login.html')


@login_required
def user_logout(request):
    print("logout")
    logout(request)
    return HttpResponseRedirect(reverse('index'))


class DeleteComplains(LoginRequiredMixin,generic.DeleteView):
    template_name = 'App/Teacher_dashboard.html'
    model = Complains
    success_url =reverse_lazy('dashboard')


@login_required
def dashboard(request):
    user_dashdata = Complains.objects.filter(author=request.user)
    ComplainsDic = {'dashdata': user_dashdata}
    return render(request, 'App/Teacher_dashboard.html', {'dashdata': user_dashdata})


class Dash(LoginRequiredMixin, generic.ListView):
    template_name='App/Dash.html'
    context_object_name='dashdata'

    def get_queryset(self):
        return Complains.objects.all()


class ComplainsCreateView(LoginRequiredMixin, generic.CreateView):
    model = Complains
    form_class = ComplainForm
    template_name = 'App/AddComplains.html'

    def form_valid(self, form):
        AddComplains = form.save(commit=False)
        # form.instance.author = self.request.user
        AddComplains.author = self.request.user
        AddComplains.save()
        return redirect('dashboard')


class NoticeBoard(LoginRequiredMixin, generic.ListView):
    template_name='App/Notice.html'
    context_object_name='Notice'

    def get_queryset(self):
        return Notice.objects.all().order_by('IssuedOn')


class NoticeCreateView(LoginRequiredMixin, generic.CreateView):
    model = Notice
    form_class = NoticeForm
    template_name = 'App/AddNotice.html'

    def form_valid(self, form):
        AddNotice = form.save(commit=False)
        AddNotice.save()
        return redirect('Notice')



class AttendentDetails(LoginRequiredMixin, generic.ListView):
    template_name='App/Attendents.html'
    context_object_name='LabAttendent'

    def get_queryset(self):
        return LabAttendent.objects.all().order_by('LabAssigned')


class FacultyDetails(LoginRequiredMixin, generic.ListView):
    template_name='App/Faculty.html'
    context_object_name='LabTeacher'

    def get_queryset(self):
        return LabTeacher.objects.all().order_by('TeacherName')


class TimeTable(LoginRequiredMixin,generic.CreateView):
    model = LabSchedule
    form_class = TimeTableForm
    template_name = 'App/TimeTable.html'
    context_object_name = 'LabSchedule'

    def get_queryset(self):
        # if self.request.method=='POST':
        #     return LabSchedule.objects.all()
        # else:
        return LabSchedule.objects.all()


from django.views.generic.edit import UpdateView


class StatusUpdate(UpdateView):
    model = Complains
    form_class = UpdateIssueStatusForm
    template_name = 'App/IssueUpdateView.html'

    def form_valid(self, form):
        issueupdate = form.save(commit=False)
        issueupdate.save()
        return redirect('dashboard_Att')

templates/App/AddComplains.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}

<h1 class="h3 text-center bg-success">ADD COMPLAINS</h1>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>
{% endblock %}

templates/App/AddNotice.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}

<h1 class="h3 text-center bg-success">ADD NOTICE</h1>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>
{% endblock %}

templates/App/Attendents.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}
<table class="table">
  <thead>
    <th>LabAssinged</th>
    <th>Name</th>
    <th>Contact</th>
  </thead>
{% if LabAttendent %}
  {% for dd in LabAttendent %}
  <tr>
    <td>{{ dd.LabAssigned }}</td>
    <td>{{ dd.AttendentName }}</td>
    <td>{{ dd.Contact }}</td>

  </tr>
  {%endfor%}
{% endif %}
</table>

{% endblock %}

templates/App/Dash.html
{% extends 'App/base.html' %}
{% block body_block %}
<div class="container-fluid">
<div class="jumbotron">
  <h1>Welcome to Attendent Dashboard</h1>
<div class="row">
  <div class="col-4">


  </div>
  <div class="col-8">
    <h3 align="center" text-align="center">Current Complains</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <th>LabName</th>
        <th>Issue</th>
        <th>Status</th>

      </thead>
{% if dashdata %}
      {% for dd in dashdata %}
      <tr>
        <td>{{ dd.author }}</td>
        <td>{{ dd.Issue }}</td>
        <td>{{ dd.ResolvedValue }}</td>


        <td><form action="{% url 'StatusUpdate' dd.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="dd_id" value="{{dd.id}}"/>
            <button type="submit" class="btn btn-danger" name="button" value="update">Update</button>
            </form>
        </td>

      </tr>
      {%endfor%}
{% endif %}
    </table>



  </div>

</div>

</div>




</div>
{% endblock %}

templates/App/Faculty.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}
<table class="table">
  <thead>
    <th>Name</th>
    <th>Contact</th>
  </thead>
{% if LabTeacher %}
  {% for dd in LabTeacher %}
  <tr>
    <td>{{ dd.TeacherName }}</td>
    <td>{{ dd.Contact }}</td>

  </tr>
  {%endfor%}
{% endif %}
</table>

{% endblock %}

templates/App/IssueUpdateView.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}

<h1 class="h3 text-center bg-success">Update Issue</h1>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>
{% endblock %}

templates/App/Notice.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}
<table class="table">
  <thead>
    <th>Issued On</th>
    <th>Notice</th>
  </thead>
{% if Notice %}
  {% for dd in Notice %}
  <tr>
    <td>{{ dd.IssuedOn }}</td>
    <td>{{ dd.Text }}</td>

  </tr>
  {%endfor%}
{% endif %}
</table>
{% if user.is_staff %}
    <div><a style="margin-top:10px;width:100%"  class="btn btn-warning transparent" href="{% url 'NoticeCreate' %}">Add Notice</a></div>
{% endif %}
{% endblock %}

templates/App/Teacher_dashboard.html
{% extends 'App/base.html' %}
{% block body_block %}
<div class="container-fluid">
<div class="jumbotron">
  <h1>Welcome to Dashboard</h1>
<div class="row">
  <div class="col-4">



    <div><a style="margin-top:10px;width:100%"  class="btn btn-warning transparent" href="{% url 'ComplainCreate' %}">Add Complains</a></div>
  </form>
  </div>
  <div class="col-8">
    <h3 align="center" text-align="center">Current Complains</h3>
    <table class="table table-striped table-bordered table-hover table-condensed">
      <thead>
        <th>LabName</th>
        <th>Issue</th>
        <th>Status</th>

      </thead>
{% if dashdata %}
      {% for dd in dashdata %}
      <tr>
        <td>{{ dd.LabName }}</td>
        <td>{{ dd.Issue }}</td>
        <td>{{ dd.ResolvedValue }}</td>


        <td><form action="{% url 'DeleteComplains' dd.id %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="dd_id" value="{{dd.id}}"/>
            <button type="submit" class="btn btn-danger" name="button" value="Delete">Delete</button>
            </form>
        </td>

      </tr>
      {%endfor%}
{% endif %}
    </table>



  </div>

</div>

</div>




</div>
{% endblock %}

templates/App/TimeTable.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}

<h1 class="h3 text-center bg-success">Search Schedule</h1>
<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{{form.as_p}}

	<button class="btn btn-success" type="submit">Yup!Done</button>
</form>
<table class="table">
  <thead>
    <th>TimeSlot</th>
    <th>Batch</th>
    <th>Subject</th>
    <th>TeacherName</th>
  </thead>
{% if TimeTable %}
  {% for dd in TimeTable %}
  <tr>
    <td>{{ dd.TimeSlot }}</td>
    <td>{{ dd.Batch }}</td>
    <td>{{ dd.Subject }}</td>
    <td>{{ dd.TeacherName }}</td>

  </tr>
  {%endfor%}
{% endif %}
</table>




{% endblock %}

templates/App/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- <meta charset="utf-8"> -->
    <title></title>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->

    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
</style>


  </head>
<body>

   <nav class="navbar navbar-default">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Lab Manager</a>
       </div>
       <div class="collapse navbar-collapse" id="myNavbar">
         <ul class="nav navbar-nav navbar-right">
           <li><a class="navbar-link" href="{% url 'index' %}">&nbsp Home </a></li>


           {% csrf_token %}
           {% if user.is_staff %}
           <li><a class="navbar-band" href="{% url 'dashboard_Att' %}">&nbsp Attendent Dashboard</a></li>
           <li><a class="navbar-link" href="{% url 'admin:index' %}">&nbsp Admin </a></li>
           <!--<li><a class="navbar-band" href="">&nbsp Register </a></li>-->
           {% endif %}



           {% if user.is_authenticated %}
           <li><a class="navbar-band" href="{% url 'Notice' %}">&nbsp Notices</a></li>
           <li><a class="navbar-link" href="{% url 'Attendent' %}">&nbsp Attendents </a></li>
           <li><a class="navbar-link" href="{% url 'TimeTable' %}">&nbsp TimeTable </a></li>
           <li><a class="navbar-link" href="{% url 'Faculty' %}">&nbsp Faculty </a></li>
           <li><a class="navbar-link" href="{% url 'dashboard'%}">&nbsp dashboard </a></li>
           <li><a class="navbar-link" href="{% url 'logout' %}">&nbsp logout </a></li>

           {% else %}
             <li><a class="navbar-link" href="{% url 'login' %}">&nbsp Login </a></li>
           {% endif %}


         </ul>
       </div>
     </div>
   </nav>






  {% block body_block %}


  {% endblock %}


  </body>
  <!-- Footer -->
  <footer class="container-fluid bg-4 text-center" style=" position:-ms-device-fixed;height:auto;
    left: 0;
    bottom: 0;
    width: 100%;">

    <!-- Copyright -->

    <p>
      DEVELOPED BY :
        <a href="https://www.linkedin.com/in/yuvraj-singh-84b3114a">Hawks</a>
        &nbsp;&nbsp;


      © 2018 Copyright:
      <a href=""> TIET</a>
      &nbsp;&nbsp;

    <!-- Copyright -->

  </footer>
  <!-- Footer -->

</html>

templates/App/index.html
{% extends 'App/base.html' %}
{% block body_block %}


  <div class="container-fluid1 bg-1 text-center">
  <h3 class="margin">Lab Management System</h3>
    <h3>WELCOME TO LAB MANAGEMENT SYSTEM TIET</h3>
</div>

{% endblock %}

templates/App/login.html
{% extends 'App/base.html' %}
{% load staticfiles %}
{% block body_block %}





<div class="login-page">
  <div ="container-fluid col-xl-5" style="border-style:inset;  border-width:2px;padding:7px; ">
<h3 class="h3 text-center bg-success" align="center">LOGIN</h3>
  <form action="{% url 'App:login' %}" method="post" >
    {% csrf_token %}
      <div class="form-group">
        <label for="Username">username</label>
        <input type="text" class="form-control"  placeholder="Enter user name" name="username">
      </div>
      <div class="form-group">
        <label for="Password">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Password">
      </div>
      <div class="form-group">
      <button type="submit" class="btn btn-primary">Submit</button>
      </div>

</div>

</div>


  </form>


{% endblock %}}